-- 1- Profitability by Region
SELECT
    B.BRANCH_REGION,
    SUM(F.BRANCH_REVENUE - F.BRANCH_EXPENSES) AS TOTAL_PROFIT
FROM FACT_TRANSACTION F
JOIN DIM_BRANCH B
  ON F.BRANCH_KEY = B.BRANCH_KEY
GROUP BY B.BRANCH_REGION
ORDER BY TOTAL_PROFIT DESC;

SELECT * FROM target_q1;


-- 2- Do High Balances Lead to Higher Investment?
SELECT
    C.CUSTOMER_TYPE,
    AVG(F.TOTAL_BALANCE)    AS AVG_BALANCE,
    AVG(F.INVESTMENT_AMOUNT) AS AVG_INVESTMENT
FROM FACT_TRANSACTION F
JOIN DIM_CUSTOMER C
  ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
 AND C.IS_CURRENT = 'Y'
GROUP BY C.CUSTOMER_TYPE;


-- 3- Transaction Activity by Account Type
SELECT
    A.ACCOUNT_TYPE,
    COUNT(*) AS TRANSACTION_COUNT,
    SUM(F.TRANSACTION_AMOUNT) AS TOTAL_TRANSACTION_AMOUNT
FROM FACT_TRANSACTION F
JOIN DIM_ACCOUNT_TYPE A
  ON F.ACCOUNT_TYPE_KEY = A.ACCOUNT_TYPE_KEY
GROUP BY A.ACCOUNT_TYPE
ORDER BY TRANSACTION_COUNT DESC;

SELECT * FROM TARGET_Q3;


-- 4- Individual vs Business Customer Ratio
SELECT
    CUSTOMER_TYPE,
    COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMER_COUNT
FROM DIM_CUSTOMER
WHERE IS_CURRENT = 'Y'
GROUP BY CUSTOMER_TYPE;

SELECT * FROM TARGET_Q4;

-- 5- Customer Concentration by Region
SELECT
    CUSTOMER_REGION,
    COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMER_COUNT
FROM DIM_CUSTOMER
WHERE IS_CURRENT = 'Y'
GROUP BY CUSTOMER_REGION
ORDER BY CUSTOMER_COUNT DESC;

-- 6- Cities Generating Highest Revenue 
SELECT
    B.BRANCH_CITY,
    SUM(F.TRANSACTION_AMOUNT) AS TOTAL_REVENUE
FROM FACT_TRANSACTION F
JOIN DIM_BRANCH B
  ON F.BRANCH_KEY = B.BRANCH_KEY
GROUP BY B.BRANCH_CITY
ORDER BY TOTAL_REVENUE DESC;

SELECT * FROM TARGET_Q6;
