-- Staging layer
SELECT * FROM stg_bank;
SELECT * FROM stg_customer;
SELECT * FROM stg_transaction;

-- Business layer
SELECT * FROM dim_account_type;
SELECT * FROM dim_investment_type;
SELECT * FROM dim_branch;
SELECT * FROM dim_customer;
SELECT * FROM fact_transaction;

-- ========================================================
-- TEST SCD TYPE 2
-- ========================================================
UPDATE stg_customer 
SET CITY = 'UPDATED_TEST'
WHERE CUSTOMER_ID = 200000;

SELECT * FROM stg_customer WHERE CUSTOMER_ID = 200000;

INSERT INTO stg_customer VALUES (1, 23, 'INSERTED_TEST', 'INSERTED_TEST', 'INSERTED_TEST', 'INSERTED_TEST', 1015);
SELECT * FROM stg_customer WHERE CUSTOMER_ID = 1;

-- RUN THE MAP TO CHECK 
SELECT * FROM dim_customer WHERE CUSTOMER_ID = 200000;
SELECT * FROM dim_customer WHERE CUSTOMER_ID = 1;

-- ========================================================
-- TEST SCD TYPE 1
-- ========================================================
UPDATE stg_bank
SET CITY = 'UPDATED_TEST'
WHERE BRANCH_ID = 1000;

SELECT * FROM stg_bank WHERE BRANCH_ID = 1000;

-- RUN THE MAP TO CHECK
SELECT * FROM DIM_BRANCH WHERE BRANCH_ID = 1000;

-- ========================================================
-- TEST FACT_TRANSACTIONS
-- ========================================================
-- RUN THE MAP 
SELECT COUNT(*) FROM fact_transaction;

-- REMOVE LAST RUN
DELETE FROM fact_transaction WHERE load_run_id = 1;

-- SEE IF JOIN ISN'T CORRECT 
SELECT * FROM fact_transaction;

WITH CTE AS (
    SELECT 
        ST.TRANSACTION_ID AS TRANSACTION_ID,
        
        NVL(DC.CUSTOMER_KEY, 0) AS CUSTOMER_KEY,
        NVL(DB.BRANCH_KEY, 0) AS BRANCH_KEY,
        DD.DATE_KEY AS DATE_KEY,
        NVL(DI.INVESTMENT_TYPE_KEY,0) AS INVESTMENT_TYPE_KEY ,
        NVL(DA.ACCOUNT_TYPE_KEY, 0) AS  ACCOUNT_TYPE_KEY,
        
        NVL(ST.TRANSACTION_AMOUNT, 0) AS TRANSACTION_AMOUNT,
        NVL(ST.INVESTMENT_AMOUNT, 0) AS INVESTMENT_AMOUNT,
        NVL(ST.TOTAL_BALANCE, 0) AS TOTAL_BALANCE,
        
        SB.EXPENSES AS EXPENSES,
        SB.FIRM_REVENUE AS FIRM_REVENUE,
        SB.PROFIT_MARGIN AS PROFIT_MARGIN
        
    FROM STG_TRANSACTION ST
    LEFT JOIN DIM_CUSTOMER DC
        ON ST.CUSTOMER_ID = DC.CUSTOMER_ID AND DC.IS_CURRENT = 'Y'
    LEFT JOIN DIM_BRANCH DB
        ON DC.BRANCH_ID = DB.BRANCH_ID
    LEFT JOIN DIM_ACCOUNT_TYPE DA
        ON DA.ACCOUNT_TYPE = ST.ACCOUNT_TYPE
    LEFT JOIN DIM_INVESTMENT_TYPE DI
        ON DI.INVESTMENT_TYPE = ST.INVESTMENT_TYPE
    LEFT JOIN DIM_DATE DD
        ON DD.FULL_DATE = ST.TRANSACTION_DATE
    LEFT JOIN STG_BANK SB
        ON SB.BRANCH_ID = DB.BRANCH_ID
)
/*
SELECT
    FT.TRANSACTION_ID,
    C.TRANSACTION_ID
FROM CTE C
FULL OUTER JOIN FACT_TRANSACTION FT
ON C.TRANSACTION_ID = FT.TRANSACTION_ID 
WHERE C.TRANSACTION_ID IS NULL OR  FT.TRANSACTION_ID IS NULL;
*/
SELECT
    FT.TRANSACTION_ID,
    C.TRANSACTION_ID,
    FT.CUSTOMER_KEY,
    C.CUSTOMER_KEY,
    FT.BRANCH_KEY,
    C.BRANCH_KEY
FROM CTE C
FULL OUTER JOIN FACT_TRANSACTION FT
ON C.TRANSACTION_ID = FT.TRANSACTION_ID 
WHERE C.TRANSACTION_ID = 300000;

